name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait before deploy (10 seconds)
        run: sleep 10

      - name: Deploy to Vercel (with retry)
        run: |
          for i in {1..2}; do
            npx vercel --prod --token $VERCEL_TOKEN --confirm && break || sleep 60
          done
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
